# Change these first
owner: PandaDaily # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Pandaily
    url: https://pandaily.com
  - name: Pandata
    url: https://pandata.pandaily.com
  - name: Decode China
    url: https://decode.pandaily.com
  - name: Pandaread
    url: https://pandaread.com
  - name: NotificationTestSite
    url: http://h.liyaodong.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.pandaily.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars1.githubusercontent.com/u/77257553?s=200&v=4
  name: Uptime
  introTitle: "Pandaily uptime monitor"
  introMessage: "Contact tech@pandaily.com for any issue/feedback."
  navbar:
    - title: Status
      href: /
    - title: Pandaily
      href: https://pandaily.com
    - title: Pandata
      href: https://pandata.pandaily.com
    - title: Twitter
      href: https://twitter.com/thePandaily

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
